# Generated by Django 4.0.4 on 2023-03-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace_time',
            new_name='attendance_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='helper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.helper'),
        ),
        migrations.AlterField(
            model_name='truck_part',
            name='Receipt',
            field=models.ImageField(upload_to='receipts/'),
        ),
    ]
