# Generated by Django 4.0.5 on 2022-07-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.attendance', verbose_name='Attendance Name')),
            ],
        ),
    ]
