# Generated by Django 4.0.4 on 2023-03-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_attendace_time_attendance_attendance_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancecounter',
            old_name='name',
            new_name='helper',
        ),
    ]
