# Generated by Django 4.0.4 on 2022-08-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_truck_distance_travelled_alter_truck_fuel_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='TruckMaintenanceCount',
            field=models.IntegerField(null=True, verbose_name='Truck Maintenance Count'),
        ),
    ]
