# Generated by Django 4.0.4 on 2022-07-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_attendance_name_alter_attendancecounter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='name',
            new_name='helperName',
        ),
    ]
