# Generated by Django 4.0.6 on 2022-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_truck_part_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_part',
            name='Receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
