# Generated by Django 4.0.5 on 2022-07-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_attendancecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecounter',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
