# Generated by Django 4.0.6 on 2022-07-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_truck_part_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='completePay',
        ),
    ]
