# Generated by Django 4.0.4 on 2022-07-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_name_helper_helpername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helperName',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
