# Generated by Django 4.0.4 on 2023-03-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_name_attendancecounter_helper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancecounter',
            old_name='helper',
            new_name='helper_name',
        ),
    ]
