# Generated by Django 4.0.4 on 2022-07-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_helper_helpername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helperName',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
