# Generated by Django 4.0.6 on 2022-08-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_truck_part_truck_used_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='Truck_Assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='website.truck'),
        ),
        migrations.AlterField(
            model_name='truck_part',
            name='Truck_Used_On',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.truck'),
        ),
    ]
