# Generated by Django 4.0.4 on 2023-03-26 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_helper_attendancecounter_helper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
