# Generated by Django 4.0.5 on 2022-07-16 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_attendancecounter_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecounter',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.attendance'),
        ),
    ]
