# Generated by Django 4.0.4 on 2022-07-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_helper_helpername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='helperName',
            new_name='name',
        ),
    ]
