# Generated by Django 4.0.4 on 2023-03-26 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_attendancecounter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
