# Generated by Django 4.0.4 on 2022-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_helpername_helper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
