# Generated by Django 4.0.4 on 2023-04-11 02:21

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_truck_part_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=website.models.generate_transaction_id, max_length=100),
        ),
    ]
