# Generated by Django 4.0.4 on 2022-07-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_helper_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='name',
            new_name='helper_name',
        ),
        migrations.RenameField(
            model_name='attendancecounter',
            old_name='name',
            new_name='helper_name',
        ),
    ]
