# Generated by Django 4.0.4 on 2022-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_profileqr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileQR',
        ),
        migrations.AddField(
            model_name='payment',
            name='completePay',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transactionID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
