# Generated by Django 4.0.4 on 2023-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_name_attendance_helper_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='helper_name',
        ),
        migrations.RemoveField(
            model_name='attendancecounter',
            name='helper_name',
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancecounter',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='helper',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
