# Generated by Django 4.0.4 on 2022-07-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_profileqr_payment_completepay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
