# Generated by Django 4.0.4 on 2022-07-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_truck_part_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck_part',
            old_name='image',
            new_name='Receipt',
        ),
    ]
