# Generated by Django 4.0.4 on 2022-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_image_truck_part_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='Plate_Num',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
