# Generated by Django 4.0.4 on 2022-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_truck_plate_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='Plate_Num',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
