# Generated by Django 4.0.4 on 2022-07-24 19:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_truck_plate_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transactionID',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
